#
# Makefile for src/sbin (sources for programs installed in /sbin)
#

TOP=../..
.include "$(TOP)/mk/os161.config.mk"

SUBDIRS=reboot halt poweroff mksfs dumpsfs sfsck test_link test_mkdir test_remove test_rename test_rmdir test_truncate test_write

.include "$(TOP)/mk/os161.subdir.mk"
